<a href="https://colab.research.google.com/github/REENA256/git-python-project/blob/main/Salary_Data_SLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
data=pd.read_csv('Salary_Data_SLR.csv')

In [17]:
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [18]:
# Independent (X)
X=data.iloc[:,0].values
X=X.reshape(-1,1)

In [19]:
# Dependent (Y)
Y= data.iloc[:,1].values

In [20]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [21]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [23]:
X_train

array([[10.3],
       [ 2.2],
       [ 1.1],
       [ 5.1],
       [10.5],
       [ 3.2],
       [ 3.9],
       [ 3.2],
       [ 8.7],
       [ 4. ],
       [ 9.5],
       [ 5.9],
       [ 7.1],
       [ 2.9],
       [ 1.5],
       [ 5.3],
       [ 4.1],
       [ 9. ],
       [ 3. ],
       [ 7.9],
       [ 6.8],
       [ 4. ],
       [ 3.7],
       [ 4.9]])

In [24]:
X_test

array([[9.6],
       [2. ],
       [8.2],
       [4.5],
       [6. ],
       [1.3]])

In [25]:
Y_train

array([122391.,  39891.,  39343.,  66029., 121872.,  54445.,  63218.,
        64445., 109431.,  55794., 116969.,  81363.,  98273.,  56642.,
        37731.,  83088.,  57081., 105582.,  60150., 101302.,  91738.,
        56957.,  57189.,  67938.])

In [26]:
Y_test

array([112635.,  43525., 113812.,  61111.,  93940.,  46205.])

In [27]:
# Y=f(X)=aX+b
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
regressor.coef_

array([9458.14107768])

In [29]:
regressor.intercept_

25004.648761371587

In [31]:
regressor.predict([[6]])

array([81753.49522743])

In [32]:
regressor.predict(X_test)

array([115802.80310707,  43920.93091672, 102561.40559832,  67566.28361092,
        81753.49522743,  37300.23216235])

In [33]:
Y_test

array([112635.,  43525., 113812.,  61111.,  93940.,  46205.])